# Generated by Django 4.0.4 on 2022-04-27 14:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('text', models.TextField(max_length=1000)),
                ('consent', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
