# Generated by Django 4.0.4 on 2022-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGREEMENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
