# Generated by Django 4.0.4 on 2022-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='tg_token',
            field=models.CharField(default=212702908, max_length=10),
            preserve_default=False,
        ),
    ]
