# Generated by Django 4.0.4 on 2022-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_info', '0002_phone_tg_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts_info',
            name='tg_token',
            field=models.CharField(default='5356589669:AAE36tnJzBCZ_NAHJ9CdZAXddNrVLhFnTjs', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='tg_token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
