# Generated by Django 4.0.4 on 2022-04-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_info', '0003_contacts_info_tg_token_alter_phone_tg_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='tg_token',
            new_name='tg_id',
        ),
    ]
