# Generated by Django 4.0.4 on 2022-04-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlephoto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
