# Generated by Django 4.0.4 on 2022-04-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_blog', '0002_alter_articlephoto_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vk_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_group_id', models.IntegerField(null=True)),
                ('vk_app_token', models.CharField(max_length=100, null=True)),
                ('vk_group_token', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='articlephoto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
